name:               discord-haskell-monad
version:            1.2.0
github:             "yutotakano/discord-haskell-monad"
license:            MIT
author:             "Yuto Takano"
maintainer:         "moa17stock@gmail.com"
copyright:          "2022 Yuto Takano"

extra-source-files:
- README.md

synopsis:           A complementary library to discord-haskell, introducing the
                    MonadDiscord monad.
category:           Network

description:        This library introduces the MonadDiscord monad, for which
                    DiscordHandler has an instance for, to make use of the
                    ReaderT IO design pattern, throwing exceptions instead of
                    attempting to reason about IO code with Eithers.

                    The monad also allows us to write polymorphic Discord-related
                    functions that can be called both from DiscordHandler as
                    usual, and from pure IO using an Auth token.

                    Please see the README either below if you are currently on
                    Hackage, or alternatively on GitHub at
                    <https://github.com/yutotakano/discord-haskell-monad#readme>

dependencies:
- aeson == 1.5.6.0
- base >= 4.7 && < 5
- bytestring >= 0.10.12.0 && < 0.11
- discord-haskell >= 1.12.0 && <= 1.13.0
- mtl == 2.2.2
- req >= 3.9.0 && < 3.10
- safe-exceptions >= 0.1.7.2 && <= 0.1.8
- text >= 1.2.4.1 && < 2

library:
  source-dirs: src
