name:               discord-haskell-monad
version:            1.0.0
github:             "yutotakano/discord-haskell-monad"
license:            MIT
author:             "Yuto Takano"
maintainer:         "moa17stock@gmail.com"
copyright:          "2021 Yuto Takano"

extra-source-files:
- README.md

synopsis:           A MonadDiscord monad to abstract away discord-haskell's
                    Either return types.
category:           Network

description:        This library provides a Monad called MonadDiscord that
                    abstracts the error return types of discord-haskell using
                    MonadThrow. It declares two instances of MonadDiscord,
                    which are DiscordHandler and ReaderT Auth.

                    Please see the README on GitHub at
                    <https://github.com/yutotakano/discord-haskell-monad#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- discord-haskell
- mtl
- req
- safe-exceptions
- text

library:
  source-dirs: src
